import type { Metadata } from "next";

import { Outfit } from "next/font/google";
import { Provider } from "@/components/provider";
import "./globals.css";
import { DarkMode } from "@/components/color-mode";

const inter = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <Provider>
          <DarkMode>{children}</DarkMode>
        </Provider>
      </body>
    </html>
  );
}
