import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Fira_Code } from "next/font/google";
import { Provider } from "@/components/provider";
import "./globals.css";
import { DarkMode } from "@/components/color-mode";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${firaCode.variable} ${openSans.variable}`}>
        <Provider>
          <DarkMode>{children}</DarkMode>
        </Provider>
      </body>
    </html>
  );
}
